import os
from detectron2.config import CfgNode as CN

def add_config(cfg):
    _C = cfg

    _C.MODEL.BACKBONE.DILATED = False
    _C.MODEL.BACKBONE.FREEZE_CONVS = 0

    _C.MODEL.FREEZE_LAYERS = CN()
    _C.MODEL.FREEZE_LAYERS.ROI_HEADS = []
    _C.MODEL.FREEZE_LAYERS.META_ARCH = []
    _C.MODEL.FREEZE_LAYERS.FAST_RCNN = []
    _C.MODEL.FREEZE_LAYERS.BOX_HEAD = []
    _C.MODEL.FREEZE_LAYERS.MASK_HEAD = []
    # _C.MODEL.ROI_HEADS.OTHER_CLASSES = True
    
    _C.MODEL.ROI_HEADS.EMBEDDING_PATH = ''

    _C.MODEL.ROI_HEADS.FINETUNE_TERMS = CN()
    _C.MODEL.ROI_HEADS.FINETUNE_TERMS.CLASSIFIER = ['lingual', 'visual']
    _C.MODEL.ROI_HEADS.FINETUNE_TERMS.BBOX = ['lingual', 'visual']
    _C.MODEL.ROI_HEADS.FINETUNE_TERMS.MASK = ['lingual', 'visual']
    _C.MODEL.ROI_HEADS.WEAK_CLASSIFIER_PROPOSAL_DIVISOR = 1
    _C.MODEL.ROI_HEADS.MULTI_BOX_HEAD = False

    _C.MODEL.PROPOSAL_GENERATOR.WEAK_RPN_SCORE_TRESHOLD = 0.99
    _C.MODEL.ROI_HEADS.TRAIN_USING_WEAK = False
    _C.MODEL.ROI_HEADS.TRAIN_PROPOSAL_REGRESSOR = True
    _C.MODEL.ROI_HEADS.WEAK_PROPOSAL_DIVISOR = 1.0

    _C.MODEL.ROI_HEADS.FAST_RCNN = CN()
    _C.MODEL.ROI_HEADS.FAST_RCNN.NAME = 'SupervisedDetectorOutputsBase'
    _C.MODEL.ROI_HEADS.FAST_RCNN.MODE = 'Pre_Softmax'

    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR = CN()
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.NAME = 'WeakDetectorOutputsBase'
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.NUM_KMEANS_CLUSTER = 3
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.GRAPH_IOU_THRESHOLD = 0.4
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.MAX_PC_NUM = 5
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.WEAK_LOSS_MULTIPLIER = 1.0
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.OICR_ITER = 3
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.FG_THRESHOLD = 0.5
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.BG_THRESHOLD = 0.1
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.MIL_MULTIPLIER = 1.0
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.DETECTOR_TEMP = 1.0
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.CLASSIFIER_TEMP = 1.0
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.REGRESSION_BRANCH = False
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.TYPE = 'OICR'
    _C.MODEL.ROI_HEADS.FAST_RCNN.WEAK_DETECTOR.OICR_REGRESSION_BRANCH = False

    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD = CN()
    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD.NAME = 'MeanSimilarity'
    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD.IN_FEATURES = ['res4']
    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD.POOLER_RESOLUTION = 14
    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD.POOLER_TYPE = "ROIAlignV2"
    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD.VISUAL_SIMILARITY_THRESHOLD = 0.02
    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD.SIMILARITY_COMBINATION = 'Sum'
    _C.MODEL.ROI_HEADS.VISUAL_ATTENTION_HEAD.TOPK = 5

    _C.DATASETS.META_TRAIN = ''
    _C.DATASETS.META_VAL = ''
    _C.DATASETS.META_SHOTS = []
    _C.DATASETS.META_VAL_SHOTS = 1
    _C.DATASETS.BASE_META = ''
    _C.DATASETS.BASE_META_SHOTS = 50
    _C.DATASETS.MODE = 'base'
    _C.DATASETS.CLASSIFIER_DATAROOT = '/h/skhandel/FewshotDetection/WSASOD/data/data_utils/data/VOCdevkit/'
    _C.DATASETS.CLASSIFIER_TRAIN = ()
    _C.DATASETS.ONLY_NOVEL_CLASSIFIER_DATA = False
    _C.INPUT.META_MIN_SIZE = 224
    _C.INPUT.META_MAX_SIZE = 480
    _C.INPUT.RESIZE_META = True
    _C.INPUT.NORMALIZE_IMAGES = False

    _C.DATASETS.FEWSHOT = CN()
    _C.DATASETS.FEWSHOT.TYPE = 'VOC'
    _C.DATASETS.FEWSHOT.NUM_SHOTS = 5
    _C.DATASETS.FEWSHOT.IS_ZERO_SHOT = False
    _C.DATASETS.FEWSHOT.SPLIT_ID = 1
    _C.DATASETS.FEWSHOT.BASE_CLASSES_ID = [0, 1, 3, 4, 6, 7, 8, 10, 11, 12, 14, 15, 16, 18, 19]
    _C.DATASETS.FEWSHOT.NOVEL_CLASSES_ID = [2, 5, 9, 13, 17]
    _C.DATASETS.WEAK_CLASSIFIER_MUTLIPLIER = 1.0
    _C.DATASETS.WEAK_CLASSIFIER_SAMPLE_NUM = -1
    _C.DATASETS.NUM_SAMPLES = 120
    _C.DATASETS.BASE_MULTIPLIER = -1.0
    _C.DATASETS.NOVEL_MULTIPLER = 0.0
    _C.DATASETS.SAMPLE_MULTIPLIER = 3
    _C.DATASETS.OVER_SAMPLE = False
    _C.DATASETS.SAMPLE_WITH_REPLACEMENT = False
    _C.DATASETS.SAMPLE_SEED = 0

    _C.DATASETS.PROPOSAL_FILES_CLASSIFIER_TRAIN = ()

    _C.TEST.MIN_EVAL_PERIOD=0
    _C.TEST.AUG = CN()
    _C.TEST.AUG.ENABLED = True
    _C.TEST.AUG.MIN_SIZES = (480, 576, 688, 864, 1200)
    _C.TEST.AUG.MAX_SIZE = 2000
    _C.TEST.AUG.FLIP = True

    _C.SOLVER.REFINEMENT_LR_FACTOR = 1.0
    _C.SOLVER.DELTA_LR_FACTOR = 1.0
    _C.SOLVER.MIL_LR_FACTOR = 1.0
    _C.SOLVER.TRAIN_ONLY_WEAK = -1